-- CREATE DATABASE AND SCHEMA
USE DATABASE SCD_CUSTOMER;
CREATE SCHEMA IF NOT EXISTS file_formats;
CREATE SCHEMA IF NOT EXISTS external_stages;
CREATE SCHEMA IF NOT EXISTS pipes;

-- CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT SCD_CUSTOMER.FILE_FORMATS.csv_file_format
    TYPE = csv
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- CREATE STORAGE INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION s3_init
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<s3-connection-role>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<bucket>/')
    COMMENT = 'CREATING CONNECTION TO S3';
DESC INTEGRATION s3_init;

-- CREATE STAGE OBJECT WITH INTEGRATION OBJECT & FILE FORMAT
CREATE OR REPLACE STAGE SCD_CUSTOMER.EXTERNAL_STAGES.stream_data_folder
    URL = "s3://<bucket>/stream-data/"
    STORAGE_INTEGRATION = s3_init
    FILE_FORMAT = SPOTIFY.FILE_FORMATS.csv_file_format;
LIST @SCD_CUSTOMER.EXTERNAL_STAGES.stream_data_folder;

-- CREATE PIPE
CREATE OR REPLACE PIPE SCD_CUSTOMER.PIPES.customer_pipe 
    AUTO_INGEST = TRUE AS
    COPY INTO SCD_CUSTOMER.CUSTOMER.CUSTOMER_RAW
    FROM @SCD_CUSTOMER.EXTERNAL_STAGES.stream_data_folder;
SHOW PIPES;
    